### ISSUE TITLE
Master Branch protection rule

### ISSUE THREAD

**Issue by Eliasrpx** [lweides/column-store#15]
- Disable the option to directly push to master
- add the workflow 'Java CI with Gradle' to the protection rule of 'master'

**Comment by Eliasrpx** [comment]
Could you grant me Write/Admin permissions for this repository

**Comment by lweides** [comment]
Not sure that's possible 😂

**Comment by Eliasrpx** [comment]
should be no?:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-teams-and-people-with-access-to-your-repository

**Comment by lweides** [comment]
Is not possible in repositories owned by a specific user. See https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/permission-levels-for-a-personal-account-repository

**Comment by Eliasrpx** [comment]
ok then I cant add it myself, but I think you just have to add the workflow 'Java CI with Gradle' to the protection rule of 'master'

**Comment by Eliasrpx** [comment]
alright.
regarding the workflow: you should be able to just add the 'build' job to the status check of the master protection rule.
[adding a rule](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule)
[required status checks](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks)

**Comment by lweides** [comment]
See this PR: https://github.com/lweides/column-store/pull/16 - it has been approved, but because of failing status checks cannot be merged
