### ISSUE TITLE
Implement API for .csv

### ISSUE THREAD

**Issue by lweides** [lweides/column-store#18]
Implement the API (#9, #10) for `.csv` files (which are row-stores)

Make sure the implementation is well tested and testable.

Maybe some test cases can be general, and not specific to the `.csv` implementation.

**Comment by Eliasrpx** [comment]
Option A: implement custom .csv reader 
Option B: use known tool

**Comment by Eliasrpx** [comment]
"Would also be nice to compare this to a very bare-bone .csv reader, which reads the records one at a time.
But don't change your implementation now, just as a thought for afterwards" ~https://github.com/lweides/column-store/pull/28#discussion_r1405458223

**Comment by lweides** [comment]
Can this be closed?
