### ISSUE TITLE
Filter add-ons/questions

### ISSUE THREAD

**Issue by Eliasrpx** [lweides/column-store#24]
proposal area for new filter add-ons & discussion area for already existing filters

**Comment by Eliasrpx** [comment]
Should we introduce a GTE, LTE, EQ MatchType for Long & Double ?
How strict do we want to be regarding StringFilters ? (case-sensitive, whitespaces, ...)

**Comment by lweides** [comment]
We could add these filter types as well, but I'm not sure how much value they will add.
Regarding StringFilters, they are (per the documentation) case-insensitive. What do you mean regarding whitespaces?
