### ISSUE TITLE
Define test data sets

### ISSUE THREAD

**Issue by lweides** [lweides/column-store#3]
Find suitable test data sets, verify if pruning them to contain only supported values is possible (with reasonable effort).

Define a format, in which the test data will be represented. Should *not* influence the benchmark results.

List the data sets in the comments below.

**Comment by Eliasrpx** [comment]
apparently a really nice dataset used for ML/Benchmarking:
- https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page

**Comment by lweides** [comment]
OTEL spans could be relevant, given we can find a proper mapping to our data-types
Logs (in general) are relevant, but the benchmark probably comes down to only string compression.
